
# Site settings
title: Shuya Liu
name: Shuya Liu
email: lsyragnarok@gmail.com
baseurl: ""
url: "https://syuuuga.github.io/"
github_username:  syuuuga
disqus_baseurl: "https://syuuuga.github.io/"
disqus_shortname: https-syuuuga-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Shuya Liu"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
